INSERT INTO SYS_USER (id,username,password) VALUES (1,'test1','test1');
INSERT INTO SYS_USER (id,username,password) VALUES (2,'test2','test2');

INSERT INTO SYS_ROLE (id,name) VALUES (1,'ROLE_ADMIN');
INSERT INTO SYS_ROLE (id,name) VALUES (2,'ROLE_USER');

INSERT INTO SYS_USER_ROLES (SYSTEM_USER_ID,ROLES_ID) VALUES (1,1);
INSERT INTO SYS_USER_ROLES (SYSTEM_USER_ID,ROLES_ID) VALUES (2,2);